import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Title(props) {
  const { nodes, materials } = useGLTF("/assets/models/title/title.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube.geometry}
        material={nodes.cube.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_1.geometry}
        material={nodes.cube_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_2.geometry}
        material={nodes.cube_2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_3.geometry}
        material={nodes.cube_3.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_4.geometry}
        material={nodes.cube_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_5.geometry}
        material={nodes.cube_5.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_6.geometry}
        material={nodes.cube_6.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_7.geometry}
        material={nodes.cube_7.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_8.geometry}
        material={nodes.cube_8.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_9.geometry}
        material={nodes.cube_9.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_10.geometry}
        material={nodes.cube_10.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_11.geometry}
        material={nodes.cube_11.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_12.geometry}
        material={nodes.cube_12.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_13.geometry}
        material={nodes.cube_13.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_14.geometry}
        material={nodes.cube_14.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_15.geometry}
        material={nodes.cube_15.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_16.geometry}
        material={nodes.cube_16.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_17.geometry}
        material={nodes.cube_17.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_18.geometry}
        material={nodes.cube_18.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_19.geometry}
        material={nodes.cube_19.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_20.geometry}
        material={nodes.cube_20.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_21.geometry}
        material={nodes.cube_21.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_22.geometry}
        material={nodes.cube_22.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_23.geometry}
        material={nodes.cube_23.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_24.geometry}
        material={nodes.cube_24.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_25.geometry}
        material={nodes.cube_25.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_26.geometry}
        material={nodes.cube_26.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_27.geometry}
        material={nodes.cube_27.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_28.geometry}
        material={nodes.cube_28.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_29.geometry}
        material={nodes.cube_29.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_30.geometry}
        material={nodes.cube_30.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_31.geometry}
        material={nodes.cube_31.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_32.geometry}
        material={nodes.cube_32.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_33.geometry}
        material={nodes.cube_33.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_34.geometry}
        material={nodes.cube_34.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_35.geometry}
        material={nodes.cube_35.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_36.geometry}
        material={nodes.cube_36.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_37.geometry}
        material={nodes.cube_37.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_38.geometry}
        material={nodes.cube_38.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_39.geometry}
        material={nodes.cube_39.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_40.geometry}
        material={nodes.cube_40.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_41.geometry}
        material={nodes.cube_41.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_42.geometry}
        material={nodes.cube_42.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_43.geometry}
        material={nodes.cube_43.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_44.geometry}
        material={nodes.cube_44.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_45.geometry}
        material={nodes.cube_45.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_46.geometry}
        material={nodes.cube_46.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_47.geometry}
        material={nodes.cube_47.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_48.geometry}
        material={nodes.cube_48.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_49.geometry}
        material={nodes.cube_49.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_50.geometry}
        material={nodes.cube_50.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_51.geometry}
        material={nodes.cube_51.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_52.geometry}
        material={nodes.cube_52.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_53.geometry}
        material={nodes.cube_53.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_54.geometry}
        material={nodes.cube_54.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_55.geometry}
        material={nodes.cube_55.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_56.geometry}
        material={nodes.cube_56.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_57.geometry}
        material={nodes.cube_57.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_58.geometry}
        material={nodes.cube_58.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_59.geometry}
        material={nodes.cube_59.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_60.geometry}
        material={nodes.cube_60.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_61.geometry}
        material={nodes.cube_61.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_62.geometry}
        material={nodes.cube_62.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_63.geometry}
        material={nodes.cube_63.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_64.geometry}
        material={nodes.cube_64.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_65.geometry}
        material={nodes.cube_65.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_66.geometry}
        material={nodes.cube_66.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_67.geometry}
        material={nodes.cube_67.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_68.geometry}
        material={nodes.cube_68.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_69.geometry}
        material={nodes.cube_69.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_70.geometry}
        material={nodes.cube_70.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_71.geometry}
        material={nodes.cube_71.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_72.geometry}
        material={nodes.cube_72.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_73.geometry}
        material={nodes.cube_73.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_74.geometry}
        material={nodes.cube_74.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_75.geometry}
        material={nodes.cube_75.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_76.geometry}
        material={nodes.cube_76.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_77.geometry}
        material={nodes.cube_77.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_78.geometry}
        material={nodes.cube_78.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_79.geometry}
        material={nodes.cube_79.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_80.geometry}
        material={nodes.cube_80.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_81.geometry}
        material={nodes.cube_81.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_82.geometry}
        material={nodes.cube_82.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_83.geometry}
        material={nodes.cube_83.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_84.geometry}
        material={nodes.cube_84.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_85.geometry}
        material={nodes.cube_85.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_86.geometry}
        material={nodes.cube_86.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_87.geometry}
        material={nodes.cube_87.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_88.geometry}
        material={nodes.cube_88.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_89.geometry}
        material={nodes.cube_89.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_90.geometry}
        material={nodes.cube_90.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_91.geometry}
        material={nodes.cube_91.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_92.geometry}
        material={nodes.cube_92.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_93.geometry}
        material={nodes.cube_93.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_94.geometry}
        material={nodes.cube_94.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_95.geometry}
        material={nodes.cube_95.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_96.geometry}
        material={nodes.cube_96.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_97.geometry}
        material={nodes.cube_97.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_98.geometry}
        material={nodes.cube_98.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_99.geometry}
        material={nodes.cube_99.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_100.geometry}
        material={nodes.cube_100.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_101.geometry}
        material={nodes.cube_101.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_102.geometry}
        material={nodes.cube_102.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_103.geometry}
        material={nodes.cube_103.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_104.geometry}
        material={nodes.cube_104.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_105.geometry}
        material={nodes.cube_105.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_106.geometry}
        material={nodes.cube_106.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_107.geometry}
        material={nodes.cube_107.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_108.geometry}
        material={nodes.cube_108.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_109.geometry}
        material={nodes.cube_109.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cube_110.geometry}
        material={nodes.cube_110.material}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/title/title.glb");
